```{r}
library(sqldf)
library(plotly)

data <- read.csv("Accidents_categorical.csv");
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Road_type FROM data GROUP BY Road_Type");
plot_ly(test, labels = ~Road_Type, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Type of roads in Accidents');
  
```

```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Weather FROM data GROUP BY Weather");
plot_ly(test, labels = ~Weather, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Type of weather during Accidents');
  
```

```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Road_Surface_Conditions FROM data GROUP BY Road_Surface_Conditions");
plot_ly(test, labels = ~Road_Surface_Conditions, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Type of road surfaces during Accidents');
  
```

```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Vehicle_Make FROM data GROUP BY Vehicle_Make");
plot_ly(test, labels = ~Vehicle_Make, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Vehicle make involved in Accidents');

```

```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Region FROM data GROUP BY Region");
plot_ly(test, labels = ~Region, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Regions of Accidents');


```

```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Vehicle_Manoeuvre FROM data GROUP BY Vehicle_Manoeuvre");
plot_ly(test, labels = ~Vehicle_Manoeuvre, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Vehicle_Manoeuvre of Accidents');
  
```

```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Speed_limit FROM data GROUP BY Speed_limit");
plot_ly(test, labels = ~Speed_limit, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Speed Limits of roads involved in Accidents');
  
```

```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, High_Wind FROM data GROUP BY High_Wind");
plot_ly(test, labels = ~High_Wind, values = ~COUNT, type = 'pie') %>%
  layout(title = 'High Wind during Accidents');
  
```

```{r}  
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Lights FROM data GROUP BY Lights");
plot_ly(test, labels = ~Lights, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Lights during Accidents');
```

```{r}  
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Age_of_Driver FROM data GROUP BY Age_of_Driver");
plot_ly(test, labels = ~Age_of_Driver, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Age of the Driver of Accidents');
  
```

```{r}

test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Age_of_Vehicle FROM data GROUP BY Age_of_Vehicle");
plot_ly(test, x = ~Age_of_Vehicle, y = ~COUNT, type = 'bar') %>%
  layout(title = 'Age of the Vehicle of Accidents');
```

```{r}

test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Junction_Detail as Junction FROM data GROUP BY Junction");
plot_ly(test, labels = ~Junction, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Junction involved in Accidents');

```

```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, X1st_Point_of_Impact FROM data GROUP BY X1st_Point_of_Impact");
plot_ly(test, labels = ~X1st_Point_of_Impact, values = ~COUNT, type = 'pie') %>%
  layout(title = '1st point of contact in Accidents');

```

```{r}

test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Propulsion_Code FROM data GROUP BY Propulsion_Code");
plot_ly(test, labels = ~Propulsion_Code, values = ~COUNT, type = 'pie') %>%
  layout(title = 'Propulsion code of vehicle in Accidents');
  
```

```{r}

test1 <- sqldf("SELECT COUNT(*) AS Count, Month_of_Year as Month FROM data GROUP BY Month_of_Year");
plot_ly(test1, x = ~Month, y = ~Count, type = 'bar') %>%
  layout(title = 'Accidents in each month')
```

```{r}
unique(data$Year)

```


```{r}
hist(data$Hour_of_Day)
```

.
```{r}


test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Driver_Journey_Purpose FROM data GROUP BY Driver_Journey_Purpose");
plot_ly(test, labels = ~Driver_Journey_Purpose, values = ~COUNT, type = 'pie') %>%
  layout(title = "Driver's journey purpose in Accidents");
  
```


```{r}
test <- fn$sqldf("SELECT COUNT(*) AS COUNT, Accident_Severity FROM data GROUP BY Accident_Severity");
plot_ly(test, labels = ~Accident_Severity, values = ~COUNT, type = 'pie') %>%
  layout(title = "Severity of Accident");


```

```{r}
hist(data$Engine_CC, breaks = 25)
```

```{r}
library(plotly)
```


